### ISSUE TITLE
this.img.decode is not a function

### ISSUE THREAD

**Issue by tong233** [wellyshen/react-cool-img#163]
# Bug Report

## Describe the Bug

Hi,
getting the error in Android：
this.img.decode is not a function
User Agent:
Mozilla/5.0 (Linux; U; Android 9; zh-CN; MZ-16s Pro Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.97 MZBrowser/8.7.0 Mobile Safari/537.36

When I change another browser ，no error but get blank img 
Quark browser User Agent:
Mozilla/5.0 (Linux; U; Android 9; zh-CN; 16s Pro Build/PKQ1.190616.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 Quark/3.8.5.129 Mobile Safari/537.36

## Additional Information

console.log(window.IntersectionObserver) has value

**Comment by wellyshen** [comment]
@tong233 If you turn of the `decode` from option (refer to [API](https://github.com/wellyshen/react-cool-img#api)), does the error go away?

**Comment by tong233** [comment]
thank you, error is gone. still have blank bug.

**Comment by wellyshen** [comment]
@tong233 Does it work well on Google Chrome?

**Comment by tong233** [comment]
@wellyshen Chrome 80 and Safari does work well, may be my browser with Chrome kernel version 57 is too low. Sorry you can ignore it. In addition, would you consider compatibility img.decode()? don't use it without support.

**Comment by wellyshen** [comment]
@tong233 I also think about it. But I'm not sure if the root cause is from `img.decode()` or `Image` API. Would you mind to help me find it out?

**Comment by tong233** [comment]
@wellyshen I'm sure is img.decode() because console.log(img.decode) get undefined on chrome  62.Look at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode) chrome need higher than 64. I think just add ``` if (decode && this.img.decode)``` on line 26

**Comment by saravmajestic** [comment]
This happens in Microsoft Edge browser as well. Setting decode: false works.

**Comment by wellyshen** [comment]
Thank you guys. Image decode has been skip via [v1.0.17](https://github.com/wellyshen/react-cool-img/releases/tag/v1.0.17).
