### ISSUE TITLE
Animate/Transition between Placeholder and Source

### ISSUE THREAD

**Issue by brunoalano** [wellyshen/react-cool-img#254]
It's possible to use some library like `motion-framer`, `react-spring` to create a transition when the image changes from placeholder to source?

**Comment by wellyshen** [comment]
@brunoalano There's an `onLoad` event for you to customize any transition you want as below:

```js
import React, { useState } from "react";
import Img from "react-cool-img";
import { useSpring, animated } from "react-spring";

const LazyImg = () => (
  const [loaded, setLoaded] = useState(false);
  const fadeOut = useSpring({ opacity: 0, from: { opacity: 1 } });

  return (
    <div>
      <animated.div style={loaded && fadeOut}>Your placeholder</animated.div>
      <Img src="https://the-image-url" onLoad={() => { setLoaded(true); } />
    </div>
  );
);
```

**Comment by haydnhkim** [comment]
@brunoalano You can add simple global css as below to make the transition work without js code.

```css
img[class*=no-js] {
  opacity: 1;
  transition: opacity 0.2s;
}
img[src^=data] {
  opacity: 0;
}
```

The order in which two styles are defined is important.
It's late, but I hope it helps.

**Comment by sparcbr** [comment]
> @brunoalano There's an `onLoad` event for you to customize any transition you want as below:
> 
> ```js
> import React, { useState } from "react";
> import Img from "react-cool-img";
> import { useSpring, animated } from "react-spring";
> 
> const LazyImg = () => (
>   const [loaded, setLoaded] = useState(false);
>   const fadeOut = useSpring({ opacity: 0, from: { opacity: 1 } });
> 
>   return (
>     <div>
>       <animated.div style={loaded && fadeOut}>Your placeholder</animated.div>
>       <Img src="https://the-image-url" onLoad={() => { setLoaded(true); } />
>     </div>
>   );
> );
> ```

Didn't work for me
