### ISSUE TITLE
Getting the error in Internet Explorer after implementing intersection-observer polyfill.

### ISSUE THREAD

**Issue by mpunit2530** [wellyshen/react-cool-img#282]
As per the steps in repo, implemented the react-cool-img with intersection-observer polyfill for internet explorer, than getting below error message.

!react-cool-img: the browser doesn't support Intersection Observer, please install polyfill to enable lazy loading: https://github.com/wellyshen/react-cool-img#intersection-observer-polyfill

<img width="1295" alt="Screenshot 2020-05-28 at 5 49 51 PM" src="https://user-images.githubusercontent.com/36926356/83140408-a9944480-a10b-11ea-8ed2-f6434ffdb070.png">

Use Case Scenario:

Used within react application, and defined it in app entry point as below
**import 'intersection-observer'**

Getting above error messages in console.

And only placeholder image is shown in IE, the real image never shows up.

Is the usage done is correct ?? Or is there is something missing

**Comment by wellyshen** [comment]
@mpunit2530 What IE version that you were using?

**Comment by mpunit2530** [comment]
Ther version on internet explorer is IE 11. I have tested yet chromium version and EDGE versions of IE

**Comment by wellyshen** [comment]
@mpunit2530 This bug should be fixed via [v1.2.0](https://github.com/wellyshen/react-cool-img/releases/tag/v1.2.0).
