### ISSUE TITLE
Custom key for image cache.

### ISSUE THREAD

**Issue by forlayo** [wellyshen/react-cool-img#390]
# Feature Request
Allow to provide custom key for image caching.

## Describe the Feature
We're using this library with images that comes from a cloud storage and in these URL its included the token to allow download it. That token changes from time to time, then the images aren't getting effectively cached.

## Describe the Solution You'd Like
Have a prop to provide the key I want to assign to an image for its cache. Then I can pass there the URL without the token. And all load attempts with different token will result on same cached image.

## Describe Alternatives You've Considered
I've considered trying to have same token during user instance but it's something not doable right now. I've also considered creating a page on my site to act as intermediary, for the shake of having a url that don't changes with SAS token.

## Additional Information
I am using your library + react + azure blob storage, with urls secured by SAS tokens.

**Comment by wellyshen** [comment]
@forlayo Thank you for giving this package a try. Before the feature kicked off, I'd like to know is there any possible to get the consist image URL from the service configuration?

**Comment by forlayo** [comment]
@wellyshen thanks for your quick answer, and apologizes for my delayed one. It's being a bit crazy these times :D

**The image url ends up being something like this**
https://<storage_domain>/2fcb20dc-dc71-42e9-83c1-140f4cda4fa3/private/<user_account_name>/attachments/zX7qzPI_1599120486480.png?st=2020-09-03T08%3A03%3A08Z&se=2020-09-03T08%3A38%3A08Z&sp=rwdl&sv=2018-03-28&sr=c&sig=3O1tJehsYB8%2F41v3prFL5AUnMx8emKncHWK57wvWWEg%3D

**Being the real URL of the assets**
https://<storage_domain>/2fcb20dc-dc71-42e9-83c1-140f4cda4fa3/private/<user_account_name>/attachments/zX7qzPI_1599120486480.png

**And parameters is where Azure Blob Storage looks for the SAS token**
?st=2020-09-03T08%3A03%3A08Z&se=2020-09-03T08%3A38%3A08Z&sp=rwdl&sv=2018-03-28&sr=c&sig=3O1tJehsYB8%2F41v3prFL5AUnMx8emKncHWK57wvWWEg%3D

It will work if not taking in care the parameters of the url for image caching, but this is for my specific situation; I could imagine scenarios for other people that this wouldn't work. 

Then I think the universal solution is to being able to provide a prop with the key for the cache, or something like that. Then library can use what it's doing actually for the cache key, if nothing provided, or the provided one.

**Comment by wellyshen** [comment]
@forlayo One thing I need to clarify is the `cache` feature of this library based on browser's caching to prevent un-necessary lazy-loading for better UX. I don't think this feature is feasible without browser's caching.
