### ISSUE TITLE
Can I get the img ref?

### ISSUE THREAD

**Issue by tong233** [wellyshen/react-cool-img#572]
Hi, when I try to use ref prop to handle image get the error:```Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()```

**Comment by tong233** [comment]
I got it resolved by onLoad e.target

**Comment by wellyshen** [comment]
@tong233 Thanks, it should be fixed in the [latest version](https://github.com/wellyshen/react-cool-img/releases).
