### ISSUE TITLE
Lazy loading isn't working although lazy attribute is true

### ISSUE THREAD

**Issue by christineschuller** [wellyshen/react-cool-img#708]
# Bug Report

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

const fields: JSX.Element[] = [];
for (let i = 1; i <= 800; i++) {
  fields.push(
    <AspectRatio ratio="1" style={{ maxWidth: "200px" }}>
      {/*source = {content.moodImage?.previews.s}*/}
      <Img
        key={i}
        src={`https://source.unsplash.com/random/?image=${i}`}
        style={{ backgroundColor: "grey", width: "480", height: "320" }}
        alt="REACT COOL IMG"
        cache
        lazy
        debounce={1000}
      />
    </AspectRatio>
  );
}

// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
export function TestPageImages(): JSX.Element {
  return (
    <>
      <AspectRatio ratio="1/5" style={{ maxWidth: "400px" }}>
        <img key={"key"} src={"https://source.unsplash.com/random"} alt="REACT COOL IMG" />
      </AspectRatio>
      <div className="mb-20 flex flex-wrap pl-5">{fields}</div>
    </>
  );
}

## Expected Behavior

It should load lazy the images while scrolling, but it loads every single image at the beginning.

## Your Environment

- Device: MacBook Pro
- OS: macOS
- Browser: Chrome

**Comment by wellyshen** [comment]
Hi @christineschuller

This library turns on the `cache` feature by default to avoid unnecessarily lazy loading for better UX. Can you change the `cache` prop to `false` to see whether the lazy loading works as expected?

**Comment by christineschuller** [comment]
Thanks for the fast response! I'll try it next week, I don't have access rn to the project. Thanks a lot! I'll let you know.

**Comment by wellyshen** [comment]
@christineschuller No problem, have a nice weekend :)

**Comment by christineschuller** [comment]
Thanks! You too :)

**Comment by ProCode2** [comment]
Had the same question, changing `cache` to false works for me!

**Comment by wellyshen** [comment]
I'd recommend to turn the cache feature on because when images are cached by browser we don't need to lazily loading them again. By doing so, the user can see the content quickly.

**Comment by christineschuller** [comment]
Unfortunately it didn't solve my problem. Could you @wellyshen maybe share a code snippet from your netlify app? Thanks in advance

**Comment by wellyshen** [comment]
@christineschuller 

Here's my code snippet: https://github.com/wellyshen/react-cool-img/blob/master/demo/App/index.tsx
You can also share a minimal reproduced code via [CodeSandbox](https://codesandbox.io) or repo with me.

**Comment by christineschuller** [comment]
https://codesandbox.io/s/competent-andras-2zuig?file=/src/App.tsx here's the link to my reproduced case. I tried also with your example but somehow it still loads everything at the beginning..

**Comment by christineschuller** [comment]
It works now. Thanks a lot :) I probably had a bug in my code or something.. it works fine now with your code snippet. Thank you once again!

**Comment by wellyshen** [comment]
@christineschuller Happy for you, keep going :)
