### ISSUE TITLE
There are many requests at the beginning

### ISSUE THREAD

**Issue by christineschuller** [wellyshen/react-cool-img#710]
# Bug Report

## Describe the Bug

There are in spite of lazy loading a lot of API calls at the beginning, as the DOM elements are still very small and are therefore in the view port.

## How to Reproduce

This "bug" appears also on your netlify app.

## CodeSandbox Link

Show me the bug on [CodeSandbox](https://codesandbox.io).

## Expected Behavior

I would like to see the API calls after the page load, so that there are less API calls at the beginning.

## Screenshots

Add screenshots to help explain your problem.

## Your Environment

- Device:  MacBook Pro
- OS:  macOS
- Browser: Chrome

## Additional Information

Any other information about the problem here.

**Comment by wellyshen** [comment]
@christineschuller Sorry for the late 😅. Yea! because I intended to demonstrate some features of this library (e.g. `retry`, `margin` etc.) to the user. However, you can explore the [API](https://github.com/wellyshen/react-cool-img#api) to meet your needs as follows:

```diff
const App: FC = () => {
     const images = [];
 
     while (images.length < num) {
-      const id = Math.floor(Math.random() * 1000) + 1;
-
       images.push(
         <Img
           key={images.length}
           css={image}
           placeholder={loadingImg}
-          src={`https://picsum.photos/id/${id}/480`}
+          src="https://picsum.photos/id/100/480"
           error={errorImg}
           alt="Demo Image"
+          cache={false}
+          observerOptions={{ rootMargin: "0px" }}
+          retry={{ count: 0 }}
         />
       );
     }
```
