### ISSUE TITLE
Use url in placeholder

### ISSUE THREAD

**Issue by MP3Martin** [wellyshen/react-cool-img#925]
I know this is probably gonna get closed, but i still want to ask you.
Is there any way i can use [image url](https://cdn.jsdelivr.net/gh/mp3martin/public-assets@master/websites/mp3martin-xyz/assets/loading-3lines.gif) as a value for placeholder?
Thank you

**Comment by wellyshen** [comment]
@MP3Martin I think it might work, just try it and let me know.

**Comment by MP3Martin** [comment]
No, it does not work. Btw  `import loadingImage from "./images/loading.gif";` converts it into **base64**. I tried fetching the image and then converting it to **base64**, but it is too slow, unpredictable and complicated.

Thank you for any solutions or tips.

**Comment by wellyshen** [comment]
@MP3Martin Does CDN faster than local image file?

**Comment by MP3Martin** [comment]
> @MP3Martin Does CDN faster than the local image file?

Yes. The point is that i need it to have input similar to `src=""`. 

**This is just a suggestion**

**Comment by MP3Martin** [comment]
If you think this is unnecessary, you can close this issue. I can live without 0.09 seconds

**Comment by wellyshen** [comment]
@MP3Martin It's OK to leave this issue open, I will take time to see if we can support this feature or not.

**Comment by TrejoCode** [comment]
> @MP3Martin It's OK to leave this issue open, I will take time to see if we can support this feature or not.

But isn't necessary, placeholder: Local image, fast

**Comment by MP3Martin** [comment]
Unnecessary "issue / feature request"
